name: PythonDebian
comment: Debian Test
discription: Test Debian python insalled
image: debian
mounts:
- hostPath: ./data
  serverPath: /Home/Python/out
- hostPath: ./test
  serverPath: /Home/Python/out2
ports:
- hostPorts:
  - 8080
  serverPort: 8080
- hostPorts:
  - 81
  serverPort: 81
containerScripts:
  instalationScript:
    scriptCommand: touch /Home/Python/out/.InstallComplete && echo InstallComplete1 && sleep 30 && echo InstallComplete2 
    entrypoint: bash
  startScript:
    scriptCommand: touch /Home/Python/out/.StartComplete && echo StartComplete1 && sleep 30 && echo StartComplete2 
    entrypoint: bash
  updateScript:
    scriptCommand: touch /Home/Python/out/.Update && echo Update1 && sleep 30 && echo Update2 
    entrypoint: bash
variables:
- name: P_Version
  description: Python version to install
  envVariable: 3.7
  defaultValue: 3.7
  userViewable: true
  userEditable: true
